variables:
  PLATFORM_MIN_VERSION: '6.5.0.0'
  CMS_EXTENSION_BRANCH: 'master'
  PLUGIN_DEPENDENCIES:
    value: >
      [
        { "name": "SwagCmsExtensions", "url": "gitlab.shopware.com/shopware/6/services/cms-extensions", "branch": "$CMS_EXTENSION_BRANCH" }
      ]

phpunit:
  services:
    -   name: $MYSQL_IMAGE
        alias: database
        entrypoint: [ 'sh', '-c', "docker-entrypoint.sh $MYSQL_CMD" ]
  script:
    -   composer dump-autoload --dev -d "${PROJECT_ROOT}/custom/plugins/${PLUGIN_NAME}"
    -   php
        -d pcov.enabled=1 -d pcov.directory=$PWD/src -d pcov.exclude='~(vendor|tests|node_modules)~'
        ${PROJECT_ROOT}/vendor/bin/phpunit
        --configuration phpunit.xml.dist
        --log-junit ${CI_PROJECT_DIR}/phpunit.junit.xml
        --colors=never
        --coverage-cobertura ${CI_PROJECT_DIR}/cobertura.xml
        --coverage-text | grep -v -E '^Shopware\\|^  Methods:' # do not output covered files lines
  parallel:
    matrix:
      -   MYSQL_IMAGE: mariadb:10.4
          DEV_IMAGE: [ 'shopware/development:8.1-composer-2', 'shopware/development:8.2-composer-2' ]
          PLATFORM_BRANCH: [ $PLATFORM_MIN_VERSION, 'trunk' ]
      -   MYSQL_IMAGE:
            - mysql:5.7
            - mariadb:10.3
          DEV_IMAGE: [ 'shopware/development:8.1-composer-2', 'shopware/development:8.2-composer-2' ]
          PLATFORM_BRANCH: [ $PLATFORM_MIN_VERSION, 'trunk' ]
          RUN_IN_MR: 'false'
      -   MYSQL_IMAGE:
            - mysql:8.0.19
          DEV_IMAGE: [ 'shopware/development:8.1-composer-2', 'shopware/development:8.2-composer-2' ]
          PLATFORM_BRANCH: [ $PLATFORM_MIN_VERSION, 'trunk' ]
          MYSQL_CMD: $MYSQL8_CMD
          RUN_IN_MR: 'false'

phpstan:
  script:
    - composer dump-autoload --dev -d "${PROJECT_ROOT}/custom/plugins/SwagCmsExtensions"
    - composer phpstan
  parallel:
    matrix:
      -   DEV_IMAGE: ['shopware/development:8.1-composer-2', 'shopware/development:8.2-composer-2' ]
          PLATFORM_BRANCH: [ $PLATFORM_MIN_VERSION, 'trunk' ]

linting:
  stage: test
  needs: []
  script:
    - $CI_PROJECT_DIR/bin/console bundle:dump
    - '(cd $CI_PROJECT_DIR/src/Administration/Resources/app/administration/ && npm ci --no-audit --prefer-offline)'
    - '(cd $CI_PROJECT_DIR/src/Storefront/Resources/app/storefront/ && npm ci --no-audit --prefer-offline)'
    - composer init:admin
    - composer init:storefront
    - composer lint:admin:ci
    - composer lint:storefront

include:
  project: 'shopware/6/product/platform'
  ref: 'trunk'
  file: '.gitlab/templates/plugin.yml'
